name: Publish Wiki

on:
  push:
    branches:
      - main # Trigger the workflow on push events to the main branch
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Grant write permission to GITHUB_TOKEN for pushing to the wiki repo

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publish Wiki Content
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs" # Specify the directory containing the wiki markdown files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
