name: Publish Wiki Documentation

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'docs/**' # Trigger if anything in docs changes
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Grant write permission to GITHUB_TOKEN for pushing to the wiki repo

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow workflow to push to the wiki
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publish Documentation to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "docs" # Path to the directory containing wiki files
